# -*- coding: utf-8 -*-
"""1>number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gn5_h1GqQeQUQMFDzquEUXS1rXWUjNxE
"""

#Author: Ricardo Vargas
#1. Int
positive_int = 99
negative_int = -2012
zero = 0

print (positive_int)
print (negative_int)
print (zero)
print(type(negative_int))
#2. Float
positive_float = 1.497
negative_float = -2.9987654
exponent_float = 3e8

print(positive_float)
print(negative_float)
print(exponent_float)
print(type(exponent_float))
#3. Complex
complex_num = -5 + 2j
print(complex_num)
print(type(complex_num))