# -*- coding: utf-8 -*-
"""1a_number_conversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v62Fpa-yi-wgsvXB3HO_gyLtRoloCuPm
"""

#Author: Ricardo Vargas

#Int
valor_positivo_int = 66

#Float
valor_negativo_float = -4.854

#Complex
valor_complex_num = 1j

#convertir de int a float
valor_positivo_float = float(valor_positivo_int)

#convertir de float a int
valor_negativo_int = int (valor_negativo_float)

#convertir de int a complex
valor_complex_a_int = complex(valor_positivo_int)

print(valor_positivo_float)
print(valor_negativo_int)
print(valor_complex_a_int)

print(type(valor_positivo_float))
print(type(valor_negativo_int))
print(type(valor_complex_a_int))