# -*- coding: utf-8 -*-
"""1c_string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bvsWzYlyY4TusXKZflN1aI3R7T6eXuOW
"""

#Author: Ricardo Vargas

# Python has class str to represent and deal with string

first_name = "Ricardo"
last_name  = 'Sandia'
nick_name  = '''Manzana'''
address    = """ Mailing Address right?
    if so, it's Hyderabad, Madhapur.
    Pin: 5234"""

mobile_num = 9617361800

print("First Name:", first_name)
print("First Name: " + first_name) # String Concatenation
print("Multi line address string: " + address)

greetings = 'Howdy'

print("Length of the string is " + str(len(greetings))) # len() for the length of the string

print(greetings + nick_name)  ## Howdy Jassi. String Concatenation

pi = 3.14   # text = 'The value of pi is ' + pi      ## NO, does not work
text = 'The value of pi is '  + str(pi)  ## need specifically to convert number to str type to print