# -*- coding: utf-8 -*-
"""1e_string_methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nnyaeQrjllCtv9c-CC393HOG02wWygO1
"""

#Author: Ricardo Vargas

first_name = "Ricardo"
last_name  = 'Sandia'
nick_name  = '''Manzana'''
address    = """ Mailing Address right?
    if so, it's Hyderabad, Madhapur.
    Pin: 5234"""

mobile_num = 9617361800

greentins = 'Hola'
print  ("El tamaño del texto 'Hola' es:" + str(len(greentins)))

print(greentins.lower() , nick_name)
print (first_name.upper(), last_name.upper())
print (last_name.capitalize())


#------------------------------------------------------------------------------------------------------#
# Method                                | True (if)                                                      #
# str.isalnum()                         | String consists of only alphanumeric characters (no symbols) #
# str.isalpha()                         | String consists of only alphabetic characters (no symbols)   #
# str.islower()                         | String’s alphabetic characters are all lower case            #
# str.isupper()                         | String’s alphabetic characters are all upper case            #
# str.isnumeric()                       | String consists of only numeric characters                   #
#------------------------------------------------------------------------------------------------------#
print(str(mobile_num).isnumeric())
print(first_name.isalpha())
print(last_name.isalnum())
print(nick_name.isupper())

reversed_first_name =''.join(reversed(first_name))
print("Reverse of {} is {}". format(first_name, reversed_first_name))