# -*- coding: utf-8 -*-
"""2_if_elfi_else.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgpSaO31nzcHdF3yERiY5hcvvAFq6BzM
"""

#Author: Ricardo Vargas

url = input ("Ingresa tu sitioweb:")

if 'http' in url:
  print ('url no es seguro')
elif 'https' in url:
  print ('un poco mas seguro')
elif url=='google.com':
  print ('si es una url')
elif url=='':
  print ('dejaste en blanco')
else:
  print ('este es tu url' + url)