# -*- coding: utf-8 -*-
"""2a_while_loop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q302grK4FpELvrpTqhYzeUEFjP2S4RRv
"""

#Author: Ricardo Vargas

import random
# While loop syntax
# while expression:
#   statement(s)
# You can use else block with while as well
# while expression:
#   statement(s)
# else:
#   statement(s)

guess_num_range = 20
num_to_be_guessed = int (guess_num_range * random.random()) +1
guess = 0

while guess != num_to_be_guessed:
  guess = int (input ("Guess the number:"))
  if guess > 0:
    if guess > num_to_be_guessed:
      print ("number is too large")
    elif guess < num_to_be_guessed:
      print ("number is too small")

  else:
    print ("te rendiste")
else: print ("Lo lograste")