# -*- coding: utf-8 -*-
"""2b_for_loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gm0-02JugMyBxf_skPISCNHvC_kn8mW5
"""

#Author: Ricardo Vargas

# for loop syntax
# for iterating_var in sequence:
#   statements(s)

# for <variable> in <sequence>:
#	<statements>
# else:
#	<statements>

port_details = {
    '22': 'ssh',
    '21': 'ftp',
    '23': 'telnet',
    '80': 'http',
    '443': 'https'
}

for port in port_details:
  print ("{} -> {}".format (port,port_details[port]))