# -*- coding: utf-8 -*-
"""2c_range.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UtDYj0CQUBOQ2y26yUiRMuJEF0xJu6Xe
"""

#Author: Ricardo Vargas

for step in range (10,100,10):
  print (step)

port_lists = [21, 22, 23, 25, 53, 80, 443, 3306, 8080, 9002, 27017]

for port in range(len(port_lists)):
  print (port_lists[port])