# -*- coding: utf-8 -*-
"""3_operaciones_aritmeticas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18tw8rYSMN4FYzZH-eyVRhYf0oTZSFc6D
"""

#Author: Ricardo Vargas

x = 50
y = 4

print('x + y =',x+y)

print('x - y =',x-y)

print('x * y =',x*y)

print('x / y =',x/y)

print('x % y =', x%y)

print('x // y =',x//y)

print('x ** y =',x**y)