# -*- coding: utf-8 -*-
"""3a_comparison_operators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLupgJmzxgkh9ATt78rcjfZrbIoxYsPW
"""

#Author: Ricardo Vargas

x = 94
y = 12

print('{} > {} is'.format(x,y),x>y)
print('{} < {} is'.format(x, y),x<y)
print('{} == {} is'.format(x,y),x==y)
print('{} != {} is'.format(x,y),x!=y)
print('{} >= {} is'.format(x,y),x>=y)
print('{} <= {} is'.format(x,y),x<=y)

name_title = 'Ricardo'
name_lowercase = 'ricardo'

print('{} > {} is'.format(name_title, name_lowercase),name_title>name_lowercase)
print('{} < {} is'.format(name_title, name_lowercase),name_title<name_lowercase)
print('{} == {} is'.format(name_title, name_lowercase),name_title==name_lowercase)
print('{} != {} is'.format(name_title, name_lowercase),name_title!=name_lowercase)
print('{} >= {} is'.format(name_title, name_lowercase),name_title>=name_lowercase)
print('{} <= {} is'.format(name_title, name_lowercase),name_title<=name_lowercase)