# -*- coding: utf-8 -*-
"""3b_assignment_operators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Gj47vrh5DGxLmzgHiow7vbGBpYWZ2wg
"""

#Author: Ricardo Vargas

# Operator	Example	Equivatent to
# =	       x = 5	  x = 5
# +=	   x += 5	    x = x + 5
# -=	   x -= 5	    x = x - 5
# *=	   x *= 5	    x = x * 5
# /=	   x /= 5   	x = x / 5
# %=	   x %= 5	    x = x % 5
# //=	   x //= 5   	x = x // 5
# **=	   x **= 5  	x = x ** 5
# &=	   x &= 5	    x = x & 5
# |=	   x |= 5	    x = x | 5
# ^=	   x ^= 5	    x = x ^ 5
# >>=	  x >>= 5	    x = x >> 5
# <<=	  x <<= 5	    x = x << 5

x = 4
print('x =', x)

x += 4
print('x =', x)

x *= 4
print('x = {}'.format(x))