# -*- coding: utf-8 -*-
"""3d_identity_operators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rrvj_Ooksk4rAL-kbDNaPjlaAXfJPN2M
"""

#Author: Ricardo Vargas

x1 = 6
y1 = 56
x2 = 'Hola'
y2 = 'Hola'
x3 = [1,2,3]
y3 = [1,2,3]

# Output: False
print(x1 is not y1)

# Output: True
print(x2 is y2)

# Output: False
print(x3 is y3)