# -*- coding: utf-8 -*-
"""4_data_structure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pXBy5071Qqo0WOQRXgJhmJzkjM4ZiuPk
"""

#Author: Ricardo Vargas

proto_list = ["http", "https", "ftp", "ssh"]
print(proto_list)

# Tuples
proto_tuple = ("http", "https", "ftp", "ssh")
print(proto_tuple)

# Dictionaries
emp_id = {
    "sid": 657387,
    "daniel": 603719,
    "jassi": 770521,
}
print(emp_id)

# Sets
proto_set = {"tcp", "icmp", "ssh", "icmp", "ftp"}
print(proto_set)